name: melonab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakhFaNum-Black.ttf
          weight: 900
        - asset: assets/fonts/YekanBakhFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakhFaNum-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YekanBakhFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/YekanBakhFaNum-Light.ttf
          weight: 300
        - asset: assets/fonts/YekanBakhFaNum-Thin.ttf
          weight: 100
