name: melonab
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.9+0

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  get: ^4.7.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    # PNG assets
    - assets/img/melonab_logo.png
    - assets/img/transparent_logo.png

    # Icon Assets
    - assets/icons/music.png
    - assets/icons/home.png
    - assets/icons/settings.png

    # Svg Assets
    - assets/svg/heart.svg
    - assets/svg/search.svg
    - assets/svg/dual_music_note.svg
    - assets/svg/music_note.svg
    - assets/svg/dot_box.svg
    - assets/svg/heart_mis_broke.svg

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakhFaNum-Black.ttf
          weight: 900
        - asset: assets/fonts/YekanBakhFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakhFaNum-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YekanBakhFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/YekanBakhFaNum-Light.ttf
          weight: 300
        - asset: assets/fonts/YekanBakhFaNum-Thin.ttf
          weight: 100
